### ISSUE TITLE
Some project wiki page fail

### ISSUE THREAD

**Issue by lintaonz** [twinslash/redmine_sidebar_toc#2]
Hi, 

I am using toc v1.0.0 and Redmine 2.3.1.stable.  After I install toc, some project's wiki start page works fine. But some don't. It just return 500 error. 

Here is my production.log

ActionView::Template::Error (undefined method `children' for nil:NilClass):
    16:         prjs.push(@project.name)
    17:         s = @subprojects
    18: else
    19:         s = @project.parent.children.visible.all
    20: end
    21:
    22: sb = s.collect{ |p|
  app/views/wiki/show.html.erb:68:in`block in _app_views_wiki_show_html_erb___579838902_103592460'
  app/helpers/application_helper.rb:1149:in `content_for'
  app/views/wiki/show.html.erb:67:in`_app_views_wiki_show_html_erb___579838902_103592460'
  app/controllers/wiki_controller.rb:99:in `show'

**Comment by gotva** [comment]
Could you please check what exactly plugin you use.
It seems that you have installed another plugin (https://github.com/gilbertf/redmine_sidebar_toc_pt) based on our one. There are not these lines of code in our plugin, but they exist in the clone, have a look https://github.com/gilbertf/redmine_sidebar_toc_pt/blob/master/app/views/wiki/_sidebar.html.erb#L14

**Comment by gotva** [comment]
I think it is not our bug

**Comment by lintaonz** [comment]
Here my environment. Thanks

Environment:
  Redmine version                          2.3.1.stable
  Ruby version                             1.9.3 (i686-linux)
  Rails version                            3.2.13
  Environment                              production
  Database adapter                         PostgreSQL
Redmine plugins:
  clipboard_image_paste                    1.0
  redmine_backlogs                         v1.0.0
  redmine_exception_handler                1.0.0
  redmine_lightbox                         0.0.6
  redmine_monitoring_controlling           0.1.1
  redmine_sidebar_toc_pt                   1.0.0

**Comment by gotva** [comment]
please pay attention that you are using redmine_sidebar_toc_pt 1.0.0 but this repository is NOT for this plugin.
The source of the plugin redmine_sidebar_toc_pt is https://github.com/gilbertf/redmine_sidebar_toc_pt

**Comment by lintaonz** [comment]
Hi Vasily,

Thanks for the reply. After I install the plugin from
https://github.com/gilbertf/redmine_sidebar_toc_pt, I still got the error.

Environment:
  Redmine version                          2.3.1.stable
  Ruby version                             1.9.3 (i686-linux)
  Rails version                            3.2.13
  Environment                              production
  Database adapter                         PostgreSQL
Redmine plugins:
  clipboard_image_paste                    1.0
  planner                                  0.4
  redmine_backlogs                         v1.0.0
  redmine_exception_handler                1.0.0
  redmine_lightbox                         0.0.6
  redmine_monitoring_controlling           0.1.1
  redmine_sidebar_toc_pt                   1.1.0

Started GET "/projects/test?jump=wiki" for 127.0.0.1 at 2013-06-05 06:41:07
+800
Processing by ProjectsController#show as HTML
  Parameters: {"jump"=>"wiki", "id"=>"test"}
  Current user: lams (id=3)
Redirected to http://localhost/projects/test/wiki
Completed 302 Found in 15ms (ActiveRecord: 2.6ms)
Started GET "/projects/test/wiki" for 60.234.55.218 at 2013-06-05 06:41:07
+1200
Processing by WikiController#show as HTML
  Parameters: {"project_id"=>"test"}
  Current user: lams (id=3)
  Rendered wiki/_content.html.erb (59.0ms)
  Rendered attachments/_links.html.erb (125.4ms)
  Rendered attachments/_form.html.erb (4.6ms)
  Rendered plugins/redmine_sidebar_toc_pt/app/views/wiki/_sidebar.html.erb
(8.7ms)
  Rendered wiki/show.html.erb within layouts/base (260.3ms)
Completed 500 Internal Server Error in 425ms
  Rendered
plugins/redmine_exception_handler/vendor/plugins/exception_notification/lib/exception_notifier/views/exception_notifier/_request.text.e
                                                     rb (2.3ms)
  Rendered
plugins/redmine_exception_handler/vendor/plugins/exception_notification/lib/exception_notifier/views/exception_notifier/_title.text.erb
                                                      (0.8ms)
  Rendered
plugins/redmine_exception_handler/vendor/plugins/exception_notification/lib/exception_notifier/views/exception_notifier/_session.text.e
                                                     rb (2.9ms)
  Rendered
plugins/redmine_exception_handler/vendor/plugins/exception_notification/lib/exception_notifier/views/exception_notifier/_title.text.erb
                                                      (0.1ms)
  Rendered
plugins/redmine_exception_handler/vendor/plugins/exception_notification/lib/exception_notifier/views/exception_notifier/_environment.te
                                                     xt.erb (59.7ms)
  Rendered
plugins/redmine_exception_handler/vendor/plugins/exception_notification/lib/exception_notifier/views/exception_notifier/_title.text.erb
                                                      (0.3ms)
  Rendered
plugins/redmine_exception_handler/vendor/plugins/exception_notification/lib/exception_notifier/views/exception_notifier/_backtrace.text
                                                     .erb (1.4ms)
  Rendered
plugins/redmine_exception_handler/vendor/plugins/exception_notification/lib/exception_notifier/views/exception_notifier/_title.text.erb
                                                      (0.1ms)
  Rendered
plugins/redmine_exception_handler/vendor/plugins/exception_notification/lib/exception_notifier/views/exception_notifier/exception_notif
                                                     ication.text.erb
(123.8ms)

ActionView::Template::Error (undefined method `children' for nil:NilClass):
    22:         prjs.push(@project.name)
    23:         s = @subprojects
    24: else
    25:         s = @project.parent.children.visible.all
    26: end
    27:
    28: sb = s.collect{ |p|
  app/views/wiki/show.html.erb:68:in`block in
_app_views_wiki_show_html_erb__109775712_90005050'
  app/helpers/application_helper.rb:1149:in `content_for'
  app/views/wiki/show.html.erb:67:in
`_app_views_wiki_show_html_erb__109775712_90005050'
  app/controllers/wiki_controller.rb:99:in `show'

**Comment by serge-xxx** [comment]
Tao, 

in your comment https://github.com/twinslash/redmine_sidebar_toc/issues/2#issuecomment-18888951
you've already mentioned that you already using redmine_sidebar_toc_pt 1.0.0

so please check where you're writing issues 
please check that this link is https://github.com/twinslash/redmine_sidebar_toc

do you see the difference between redmine_sidebar_toc and  redmine_sidebar_toc_pt

these are two DIFFERENT plugins :)))

please repost your issue there https://github.com/gilbertf/redmine_sidebar_toc_pt or contact this guy https://github.com/gilbertf

we could not fix this because it is not functionality of our plugin :)

Thank you,
Serge.

**Comment by lintaonz** [comment]
Oh, sorry about that. I will raise the issue to the correct author.

Thanks,
